/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessContractSol from "./accessContract.sol";
export type { accessContractSol };
import type * as greeterSol from "./greeter.sol";
export type { greeterSol };
export * as factories from "./factories";
export type { AccessContract } from "./accessContract.sol/AccessContract";
export { AccessContract__factory } from "./factories/accessContract.sol/AccessContract__factory";
export type { Greeter } from "./greeter.sol/Greeter";
export { Greeter__factory } from "./factories/greeter.sol/Greeter__factory";
